version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 10
    groups:
      cargo-dependencies:
        # group minor and patch updates for dependencies
        # major updates will open their own PR
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        # group minor and patch updates for dependencies
        # major updates will open their own PR
        update-types: ["minor", "patch"]
