name: aur

on: [push, pull_request]

jobs:
  aur-publish:
    name: Publish to AUR
    runs-on: ubuntu-latest
    container: archlinux/base

    steps:
      - name: Publish
        run: |
          pacman -Sy --needed --noconfirm sudo git binutils openssh && \
          useradd builduser -m && \
          su builduser -c "
            echo ${{ secrets.SSH_PUBLIC_KEY }} > ~/.ssh/id_rsa.pub && \
            echo ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/id_rsa && \
            cd ~ && \
            git clone ssh://aur@aur.archlinux.org/dotenv-linter-bin.git && \
            cd dotenv-linter-bin && \
            GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1` | sed "s/v//")
            sed -i \"s/pkgver=.*/pkgver=$GIT_TAG\" PKGBUILD && \
            git status && \
            git add . && \
            git commit -m 'release VERSION' && \
            git push origin master
          "
