name: misspell
on: pull_request

jobs:
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: reviewdog/action-misspell@v1
        with:
          locale: "UK"
